// Mirrors signaling/src/session-id.js — the two packages don't share a
// runtime (browser vs. Node), so the ~10-line contract (alphabet, length,
// pattern) is duplicated on purpose rather than pulled cross-package.
const ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
const LENGTH = 8;

export const SESSION_PATTERN = /^[A-Za-z0-9]{8}$/;

/**
 * Cryptographically random pairing code, generated by the TV when it starts
 * a phone-control session (docs/12-controle-por-celular.md §6, step 1).
 */
export function generateSessionCode(): string {
  const bytes = new Uint32Array(LENGTH);
  crypto.getRandomValues(bytes);
  let code = '';
  for (let i = 0; i < LENGTH; i += 1) {
    code += ALPHABET[bytes[i] % ALPHABET.length];
  }
  return code;
}

export function isValidSessionCode(session: unknown): session is string {
  return typeof session === 'string' && SESSION_PATTERN.test(session);
}
